"""
src/jira/api_client.py
───────────────────────
Jira REST API v3 Client.
In this project, Jira data is represented via jira_tickets_synthetic
(generated by scripts/setup_db.py) because Jira Cloud requires
an Atlassian Cloud licence.

This module provides the live integration scaffolding —
swap in your Atlassian credentials and it will pull real ticket data.
"""

import os
from datetime import datetime, timedelta, timezone
from typing import Optional

import pandas as pd
from loguru import logger

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# ── Jira credentials from environment ────────────────────
JIRA_BASE_URL = os.getenv("JIRA_BASE_URL", "")        # e.g. https://yourorg.atlassian.net
JIRA_EMAIL    = os.getenv("JIRA_EMAIL",    "")
JIRA_API_TOKEN = os.getenv("JIRA_API_TOKEN", "")


def _get_jira_client():
    """Return a Jira session with Basic Auth, or None if unconfigured."""
    if not all([JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN]):
        logger.info(
            "Jira credentials not configured (JIRA_BASE_URL / JIRA_EMAIL / "
            "JIRA_API_TOKEN). Using synthetic ticket data."
        )
        return None

    try:
        import requests
        session = requests.Session()
        session.auth  = (JIRA_EMAIL, JIRA_API_TOKEN)
        session.headers.update({"Accept": "application/json"})

        # Verify connectivity
        r = session.get(f"{JIRA_BASE_URL}/rest/api/3/myself", timeout=10)
        r.raise_for_status()
        display = r.json().get("displayName", "unknown")
        logger.info(f"Jira connected as: {display}")
        return session
    except Exception as e:
        logger.warning(f"Jira connection failed: {e}. Using synthetic data.")
        return None


def fetch_resolved_tickets(
    project_key: str,
    days_back:   int = 180,
    max_results: int = 500,
) -> pd.DataFrame:
    """
    Fetch resolved Jira issues for a given project.

    Args:
        project_key:  Jira project key (e.g. 'ENG', 'DATA')
        days_back:    How many days of history to fetch
        max_results:  Maximum issue count per request

    Returns:
        DataFrame with columns matching jira_tickets_synthetic schema
    """
    session = _get_jira_client()
    if session is None:
        logger.info("Returning empty Jira DataFrame — using synthetic data instead")
        return pd.DataFrame()

    since    = (datetime.now(timezone.utc) - timedelta(days=days_back)).strftime("%Y-%m-%d")
    jql      = (
        f'project = {project_key} AND status = Done '
        f'AND resolutiondate >= "{since}" ORDER BY resolutiondate DESC'
    )
    rows     = []
    start_at = 0

    while True:
        params = {
            "jql":        jql,
            "startAt":    start_at,
            "maxResults": min(100, max_results - len(rows)),
            "fields":     "summary,assignee,created,resolutiondate,priority,story_points,status",
        }
        try:
            r = session.get(
                f"{JIRA_BASE_URL}/rest/api/3/search",
                params=params, timeout=15
            )
            r.raise_for_status()
            data   = r.json()
            issues = data.get("issues", [])
            if not issues:
                break

            for issue in issues:
                fields   = issue.get("fields", {})
                created  = _parse_jira_dt(fields.get("created"))
                resolved = _parse_jira_dt(fields.get("resolutiondate"))
                cycle    = 0.0
                if created and resolved and resolved > created:
                    cycle = (resolved - created).total_seconds() / 3600

                assignee = fields.get("assignee") or {}
                rows.append({
                    "jira_issue_id":               issue.get("key", ""),
                    "user_id":                     None,  # Mapped later via github_username
                    "department":                  None,  # Enriched by preprocessor
                    "created_at":                  created.isoformat() if created else "",
                    "resolved_at":                 resolved.isoformat() if resolved else "",
                    "cycle_time_hours":            round(cycle, 2),
                    "story_points":                fields.get("story_points") or 1,
                    "priority":                    (fields.get("priority") or {}).get("name", "Medium"),
                    "period":                      "After",   # Live data = post-adoption
                    "avg_ticket_resolution_hours": 0.0,       # Computed in bulk
                    "jira_tickets_closed":         1,
                })

            start_at += len(issues)
            if start_at >= data.get("total", 0) or len(rows) >= max_results:
                break

        except Exception as e:
            logger.error(f"Jira API error: {e}")
            break

    df = pd.DataFrame(rows)
    logger.info(f"Fetched {len(df)} Jira tickets from project {project_key}")
    return df


def _parse_jira_dt(dt_str: Optional[str]) -> Optional[datetime]:
    """Parse Jira ISO datetime string."""
    if not dt_str:
        return None
    for fmt in ["%Y-%m-%dT%H:%M:%S.%f%z", "%Y-%m-%dT%H:%M:%S%z"]:
        try:
            return datetime.strptime(dt_str[:26], fmt[:len(fmt)])
        except (ValueError, TypeError):
            pass
    return None
